resolver: lts-8.23

packages:
  - '.'
  - location:
      git: https://github.com/rootmos/haskeline.git
      commit: bcd94f5cc0c4e919cbda3bb43dde482cac56dd51

flags:
  haskeline:
    brick: true

extra-package-dbs: []

system-ghc: true
