resolver: lts-8.23

packages:
  - '.'
  - location:
      git: https://github.com/rootmos/haskeline.git
      commit: 48905be8dd64e7df2cba0f247d48ef3348ad13de

flags:
  haskeline:
    brick: true

extra-package-dbs: []

system-ghc: true
